export const commons = {
  domestic: [
    {
      province: '甘肃省',
      country: '中国',
      jp: 'AKS',
      name: '阿克塞哈萨克族自治县',
      id: '334',
      qp: 'Aksai Kazakh Autonomous County',
      ilid: '1000001',
    },
    {
      province: '甘肃省',
      country: '中国',
      jp: 'ANQ',
      name: '安宁区',
      id: '279',
      qp: 'Anning District',
      ilid: '1000001',
    },
    {
      province: '北京市',
      country: '中国',
      jp: 'bj',
      name: '北京',
      id: '124',
      qp: 'beijing',
      ilid: '1000001',
    },
    {
      province: '云南省',
      country: '中国',
      jp: 'DLB',
      name: '大理白族自治州',
      id: '3506',
      qp: 'Dali Bai Autonomous Prefecture',
      ilid: '1000001',
    },
    {
      province: '广东省',
      country: '中国',
      jp: 'GZS',
      name: '广州市',
      id: '383',
      qp: 'Guangzhou City',
      ilid: '1000001',
    },
    {
      province: '湖北省',
      country: '中国',
      jp: 'JMS',
      name: '荆门市',
      id: '1638',
      qp: 'Jingmen City',
      ilid: '1000001',
    },
    {
      province: '江苏省',
      country: '中国',
      jp: 'NJS',
      name: '南京市',
      id: '1917',
      qp: 'Nanjing City',
      ilid: '1000001',
    },
    {
      province: '广东省',
      country: '中国',
      jp: 'SZS',
      name: '深圳市',
      id: '407',
      qp: 'Shenzhen',
      ilid: '1000001',
    },
  ],
  foreign: [
    {
      province: '',
      country: '日本',
      jp: 'HIJ',
      name: '广岛',
      id: '3996',
      qp: 'HIROSHIMA',
      ilid: '1000009',
    },
    {
      province: '',
      country: '法国',
      jp: 'CFE',
      name: '克莱蒙费朗',
      id: '4104',
      qp: 'CLERMONT-FERRAND',
      ilid: '1000015',
    },
    {
      province: '',
      country: '美国',
      jp: 'LAX',
      name: '洛杉矶',
      id: '4150',
      qp: 'LOS ANGELES',
      ilid: '1000002',
    },
    {
      province: '',
      country: '美国',
      jp: 'NYC',
      name: '纽约',
      id: '4310',
      qp: 'NEW YORK',
      ilid: '1000002',
    },
    {
      province: '',
      country: '韩国',
      jp: 'SEL',
      name: '首尔',
      id: '3980',
      qp: 'SEOUL',
      ilid: '1000007',
    },
    {
      province: '',
      country: '中国台湾',
      jp: 'tb',
      name: '台北',
      id: '3783',
      qp: 'taibei',
      ilid: '1000005',
    },
    {
      province: '',
      country: '中国香港',
      jp: 'HK',
      name: '香港',
      id: '3958',
      qp: 'HongKong',
      ilid: '1000003',
    },
  ],
}

export const groups = {
  domestic: [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'J',
    'K',
    'L',
    'M',
    'N',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'W',
    'X',
    'Y',
    'Z',
  ],
  foreign: [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ],
}

export const cityList = {
  domestic: {
    A: [
      {
        province: '四川省',
        country: '中国',
        jp: 'ABZ',
        name: '阿坝藏族羌族自治州',
        id: '3084',
        qp: 'Aba Tibetan and Qiang Autonomous Prefecture',
        ilid: '1000001',
      },
      {
        province: '甘肃省',
        country: '中国',
        jp: 'AKS',
        name: '阿克塞哈萨克族自治县',
        id: '334',
        qp: 'Aksai Kazakh Autonomous County',
        ilid: '1000001',
      },
    ],
    B: [
      {
        province: '吉林省',
        country: '中国',
        jp: 'BCS',
        name: '白城市',
        id: '2200',
        qp: 'Baicheng',
        ilid: '1000001',
      },
      {
        province: '广西壮族自治区',
        country: '中国',
        jp: 'BSS',
        name: '百色市',
        id: '668',
        qp: 'Baise',
        ilid: '1000001',
      },
      {
        province: '海南省',
        country: '中国',
        jp: 'BSL',
        name: '白沙黎族自治县',
        id: '985',
        qp: 'Baisha Li Autonomous County',
        ilid: '1000001',
      },
      {
        province: '吉林省',
        country: '中国',
        jp: 'BSS',
        name: '白山市',
        id: '2187',
        qp: 'Baishan City',
        ilid: '1000001',
      },
      {
        province: '甘肃省',
        country: '中国',
        jp: 'BYQ',
        name: '白银区',
        id: '296',
        qp: 'Baiyin District',
        ilid: '1000001',
      },
    ],
    C: [
      {
        province: '',
        country: '中国',
        jp: 'test1',
        name: '测试省1',
        id: '1011528792633574400',
        qp: '',
        ilid: '1000001',
      },
    ],
    D: [
      {
        province: '辽宁省',
        country: '中国',
        jp: 'DLS',
        name: '大连市',
        id: '2232',
        qp: 'Dalian City',
        ilid: '1000001',
      },
    ],
    E: [
      {
        province: '内蒙古自治区',
        country: '中国',
        jp: 'EED',
        name: '鄂尔多斯市',
        id: '2371',
        qp: 'Ordos City',
        ilid: '1000001',
      },
    ],
    F: [
      {
        province: '广西壮族自治区',
        country: '中国',
        jp: 'FCG',
        name: '防城港市',
        id: '644',
        qp: 'Fangchenggang',
        ilid: '1000001',
      },
    ],
    G: [
      {
        province: '甘肃省',
        country: '中国',
        jp: 'GGX',
        name: '甘谷县',
        id: '306',
        qp: 'Gangu County',
        ilid: '1000001',
      },
    ],
    H: [
      {
        province: '黑龙江省',
        country: '中国',
        jp: 'HEB',
        name: '哈尔滨市',
        id: '1251',
        qp: 'Harbin City',
        ilid: '1000001',
      },
    ],
    J: [
      {
        province: '黑龙江省',
        country: '中国',
        jp: 'JMS',
        name: '佳木斯市',
        id: '1338',
        qp: 'Jiamusi',
        ilid: '1000001',
      },
    ],
    K: [
      {
        province: '河南省',
        country: '中国',
        jp: 'KFS',
        name: '开封市',
        id: '1402',
        qp: 'Kaifeng',
        ilid: '1000001',
      },
    ],
    L: [
      {
        province: '广西壮族自治区',
        country: '中国',
        jp: 'LBS',
        name: '来宾市',
        id: '699',
        qp: 'Laibin City',
        ilid: '1000001',
      },
    ],
    M: [
      {
        province: '甘肃省',
        country: '中国',
        jp: 'MJQ',
        name: '麦积区',
        id: '303',
        qp: 'Maiji District',
        ilid: '1000001',
      },
    ],
    P: [
      {
        province: '辽宁省',
        country: '中国',
        jp: 'PJS',
        name: '盘锦市',
        id: '2300',
        qp: 'Panjin City',
        ilid: '1000001',
      },
    ],
    Q: [
      {
        province: '贵州省',
        country: '中国',
        jp: 'QDN',
        name: '黔东南苗族侗族自治州',
        id: '780',
        qp: 'Qiandongnan Miao and Dong Autonomous Prefecture',
        ilid: '1000001',
      },
    ],
    R: [
      {
        province: '西藏自治区',
        country: '中国',
        jp: 'RKZ',
        name: '日喀则市',
        id: '3344',
        qp: 'Shigatse',
        ilid: '1000001',
      },
    ],
    N: [
      {
        province: '江西省',
        country: '中国',
        jp: 'NCS',
        name: '南昌市',
        id: '2037',
        qp: 'Nanchang',
        ilid: '1000001',
      },
    ],
    S: [
      {
        province: '河南省',
        country: '中国',
        jp: 'SMX',
        name: '三门峡市',
        id: '1515',
        qp: 'Sanmenxia',
        ilid: '1000001',
      },
    ],
    T: [
      {
        province: '新疆维吾尔自治区',
        country: '中国',
        jp: 'TCD',
        name: '塔城地区',
        id: '3248',
        qp: 'Tacheng Area',
        ilid: '1000001',
      },
    ],
    W: [
      {
        province: '海南省',
        country: '中国',
        jp: 'WNS',
        name: '万宁市',
        id: '899',
        qp: 'Wanning City',
        ilid: '1000001',
      },
    ],
    X: [
      {
        province: '甘肃省',
        country: '中国',
        jp: 'XHX',
        name: '夏河县',
        id: '381',
        qp: 'Xiahe County',
        ilid: '1000001',
      },
    ],
    Y: [
      {
        province: '四川省',
        country: '中国',
        jp: 'YAS',
        name: '雅安市',
        id: '3064',
        qp: "Ya'An City",
        ilid: '1000001',
      },
    ],
    Z: [
      {
        province: '重庆市',
        country: '中国',
        jp: 'zxc',
        name: '万州02',
        id: '990508897972262912',
        qp: '',
        ilid: '1000001',
      },
    ],
  },
  foreign: {},
}
